micronaut:
  application:
    name: management-cards
  server:
    port: 8072

  jms:
    sqs:
      enabled: true

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_DEFAULT_REGION}
  dynamodb:
    table-name: 'cards'
  sqs:
    card-application-queue-name: 'card-application'