micronaut:
  application:
    name: manage-cards
  server:
    port: 8072

  jms:
    sqs:
      enabled: true

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_DEFAULT_REGION}

  dynamodb:
    endpoint: ${AWS_DYNAMODB_ENDPOINT:}
    tables:
      cards:
        table-name: ${AWS_DYNAMODB_CARDS_TABLE_NAME}
        global-secondary-indexes:
          cards-by-bank-account-id:
            name: ${AWS_DYNAMODB_CARDS_BY_BANK_ACCOUNT_ID_GSI_NAME}
            read-capacity-units: ${AWS_DYNAMODB_CARDS_BY_BANK_ACCOUNT_ID_GSI_READ_CAPACITY_UNITS:2}
            write-capacity-units: ${AWS_DYNAMODB_CARDS_BY_BANK_ACCOUNT_ID_GSI_WRITE_CAPACITY_UNITS:2}