micronaut:
  banner: true
  application:
    name: add-cards
  server:
    port: 8071

  jms:
    sqs:
      enabled: true

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_DEFAULT_REGION}

  dynamodb:
    endpoint: ${AWS_DYNAMODB_ENDPOINT:}
    tables:
      cards:
        table-name: ${AWS_DYNAMODB_CARDS_TABLE_NAME}
        global-secondary-indexes:
          cards-by-bank-account-id:
            name: ${AWS_DYNAMODB_CARDS_BY_BANK_ACCOUNT_ID_GSI_NAME}
  sqs:
    endpoint: ${AWS_SQS_ENDPOINT:}
    queues:
      card-application-queue:
        name: ${AWS_SQS_CARD_APPLICATION_QUEUE_NAME}
      card-application-dead-letter-queue:
        name: ${AWS_SQS_CARD_APPLICATION_DLQ_NAME}