micronaut:
  banner: true
  application:
    name: add-cards
  server:
    port: 8071

  jms:
    sqs:
      enabled: true

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_DEFAULT_REGION}
  dynamodb:
    table-name: 'cards'
    endpoint: ${AWS_DYNAMODB_ENDPOINT:}
  sqs:
    card-application-queue-name: 'card-application'
    endpoint: ${AWS_SQS_ENDPOINT:}
