micronaut:
  application:
    name: cards-management-service
  server:
    port: 8072

  jms:
    sqs:
      enabled: true

aws:
  region: ${AWS_DEFAULT_REGION}

  dynamodb:
    tables:
      cards:
        table-name: ${AWS_DYNAMODB_CARDS_TABLE_NAME}
  sqs:
    queues:
      card-application-queue:
        name: ${AWS_SQS_CARD_APPLICATION_QUEUE_NAME}

redis:
  enabled: true
  uri:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  ssl: false
  pool:
    enabled: false
    max-size: 10