micronaut:
  banner: true
  application:
    name: cards-process-service
  server:
    port: 8071

  jms:
    sqs:
      enabled: true

aws:
  region: ${AWS_DEFAULT_REGION}

  dynamodb:
    tables:
      cards:
        table-name: ${AWS_DYNAMODB_CARDS_TABLE_NAME}
  sqs:
    queues:
      card-application-queue:
        name: ${AWS_SQS_CARD_APPLICATION_QUEUE_NAME}