micronaut:
  banner: true
  application:
    name: add-cards
  server:
    port: 8071

  jms:
    sqs:
      enabled: true

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_DEFAULT_REGION}

  dynamodb:
    tables:
      cards:
        table-name: ${AWS_DYNAMODB_CARDS_TABLE_NAME}
  sqs:
    queues:
      card-application-queue:
        name: ${AWS_SQS_CARD_APPLICATION_QUEUE_NAME}