micronaut:
  banner: true
  application:
    name: cards-management-service
  server:
    port: 8073

aws:
  region: ${AWS_DEFAULT_REGION}

  dynamodb:
    tables:
      cards:
        table-name: ${AWS_DYNAMODB_CARDS_TABLE_NAME}
        global-secondary-indexes:
          cards-by-bank-account-id:
            name: ${AWS_DYNAMODB_CARDS_BY_BANK_ACCOUNT_ID_GSI_NAME}

graphql:
  enabled: true
  graphiql:
    enabled: true

jackson:
  serialization-inclusion: ALWAYS
