name: On Push - CI Pipeline

on:
  push:
    paths:
      - 'cards-management-service/**'
      - 'cards-core-service/**'
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up JDK and Cache Maven Dependencies
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 21
          cache: maven

      - name: Compile and Run Unit Tests with JaCoCo
        run: |
          mvn clean test -pl cards-management-service -am --batch-mode

      - name: Debug JaCoCo File Generation
        run: ls -al cards-management-service/target

      - name: Upload Unit Test Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: cards-management-jacoco-unit-tests-exec
          path: cards-management-service/target/jacoco-unit-tests.exec
