name: On Push - Process Service Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "process-service/**"
      - "core-service/**"
      - ".github/workflows/on-push-cards-process-service.yml"

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read   # Required for checking out the repo

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up JDK and Cache Maven Dependencies
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 21
          cache: maven

      - name: Build JAR with Maven (Only Modified Modules)
        run: |
          mvn clean package -pl process-service -am --batch-mode

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::831926591127:role/github-actions-role
          aws-region: us-east-1

      - name: Upload Process Cards JAR to S3 bucket
        run: |
          aws s3 cp process-service/target/process-service-0.1.jar s3://cards-process-service-lambda-files-prod/
