name: On Push - CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "management-service/**"
      - "core-service/**"
      - ".github/workflows/on-push-cards-management-service.yml"

env:
  LOCALSTACK_VERSION: "3.7.0"
  AWS_REGION: "us-east-1"
  ECR_PUBLIC_URI: "public.ecr.aws/e0g3c1r4/cards/management-service"
  ECR_REPOSITORY: "cards/management-service"
  IMAGE_TAG: "latest"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up JDK and Cache Maven Dependencies
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 21
          cache: maven

      - name: Build JAR with Maven (Only Modified Modules)
        run: |
          mvn clean package -pl management-service,core-service -am --batch-mode

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region ${{ env.AWS_REGION }} \
            | docker login --username AWS --password-stdin public.ecr.aws

#      - name: Build, Tag, and Push the Docker image
#        run: |
#          # Navigate to the directory containing your Dockerfile
#          cd management-service
#
#          # Build the Docker image
#          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
#
#          # Tag it for the public ECR repository
#          docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_PUBLIC_URI:$IMAGE_TAG
#
#          # Push to Public ECR
#          docker push $ECR_PUBLIC_URI:$IMAGE_TAG
      - name: Build, Tag, and Push the Docker Image to Private ECR
        run: |
          # Navigate to the directory containing your Dockerfile
          cd management-service
          
          # Build the Docker image
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          
          # Tag it for the private ECR repository
          docker tag $ECR_REPOSITORY:$IMAGE_TAG \
            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
          
          # Push to Private ECR
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG