name: On Push - Management Service Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "management-service/**"
      - "core-service/**"
      - ".github/workflows/on-push-cards-management-service.yml"

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read   # Required for checking out the repo

env:
  AWS_REGION: "us-east-1"
  ECR_REPOSITORY: "cards/management-service"
  IMAGE_TAG: "latest"


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up JDK and Cache Maven Dependencies
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 21
          cache: maven

      - name: Build JAR with Maven (Only Modified Modules)
        run: |
          mvn clean package -pl management-service -am --batch-mode

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR (Private)
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} \
            | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: Build, Tag, and Push the Docker Image to Private ECR
        run: |
          # Navigate to the directory containing your Dockerfile
          cd management-service
          
          # Build the Docker image
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          
          # Tag it for the private ECR repository
          docker tag $ECR_REPOSITORY:$IMAGE_TAG \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
          
          # Push to Private ECR
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
